# Generated by Django 3.0.8 on 2020-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('url', models.URLField()),
                ('service_email', models.EmailField(max_length=120)),
                ('service_phone', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='')),
                ('terms', models.TextField()),
                ('bill_country', models.CharField(max_length=2)),
                ('country_of_residence', models.CharField(max_length=2)),
                ('activation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
