# Generated by Django 3.0.8 on 2020-07-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20200729_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
