# Generated by Django 3.0.8 on 2020-07-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20200729_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
