# Generated by Django 3.0.8 on 2020-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20200729_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
